### ISSUE TITLE
Webloader slows page significantly

### ISSUE THREAD

**Issue by srigi** [janmarek/WebLoader#107]
Given webloader configuration:

```
webloader:
  css:
    default:
      sourceDir: %appDir%/../assets/styles
      files:
        - homepage.scss
      fileFilters:
        - @wlScssFilter
```

when I use classic *control* macro:

```
{control css}
```

page delivery is really delayed significantly:

![screen shot 2015-09-24 at 17 11 22](https://cloud.githubusercontent.com/assets/295197/10077153/5f1b1d8a-62df-11e5-83f5-58519833f3b8.png)

When I change macro to:

```
{control css 'homepage.scss'}
```

and remove stylesheet from `files` in config, TTFB is OK:

![screen shot 2015-09-24 at 17 13 49](https://cloud.githubusercontent.com/assets/295197/10077260/d6a7ac7e-62df-11e5-8b85-d80b2c0ac0d3.png)

`watchFiles` is not present in config during test. I tested on `4a7ac58`.
Any ideas?
