### ISSUE TITLE
Problem with pickadate.js

### ISSUE THREAD

**Issue by smelikmartin** [janmarek/WebLoader#119]
If i use pickadate.js (http://amsul.ca/pickadate.js/date/) with webloader pickadate is failing with message "Uncaught TypeError: $(...).pickadate is not a function"

```yml
js:
	default:
		files:
			- %wwwDir%/assets/js/jquery-1.11.2.min.js
			- %wwwDir%/pickadate/picker.js
			- %wwwDir%/pickadate/picker.date.js
```

In case of direct include to layout via 'script' tag all works properly. Where can be problem? If i watch to jsloader file pickadate is included but not work properly.
