### ISSUE TITLE
Problem with Twitter Bootstrap progress bars CSS

### ISSUE THREAD

**Issue by stanleyk** [janmarek/WebLoader#42]
In the Twitter Bootstrap CSS, at the place where it defines "progress-bar-stripes", WebLoader fails while minifying it on production.

Original CSS:

``` css
@-webkit-keyframes progress-bar-stripes {
  from {
    background-position: 40px 0;
  }
  to {
    background-position: 0 0;
  }
}
```

Expected output (as it is in bootstrap.min.css):

``` css
@-webkit-keyframes progress-bar-stripes{from{background-position:40px 0}to{background-position:0 0}}
```

Real output that does not work:

``` css
@-webkit-keyframes "progress-bar-stripes"{from{background-position:40px 0;}to{background-position:0 0;}}
```
